included:
  - ../GiniVision
  - Example Swift
  - Tests/

excluded:
  - Pods/

disabled_rules: # rule identifiers to exclude from running
  - trailing_newline
  - trailing_whitespace
  - large_tuple
  - identifier_name
  - force_cast
  - nesting
  - opening_brace
  - function_body_length
  - operator_whitespace
  - nesting

force_try:
  severity: warning # explicitly
line_length:
- 150 # warning
- 600 # error
function_body_length:
- 50 # warning
- 60 # error

identifier_name: warning
shorthand_operator: warning
