source 'https://github.com/gini/gini-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'GiniVision_Example' do
    pod 'GiniVision', :path => '../'
    pod 'Gini-iOS-SDK'
    
    target 'GiniVision_Tests' do
        inherit! :search_paths
    end
    
    target 'GiniVision_UITests' do
        inherit! :search_paths
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
