source 'https://github.com/gini/gini-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

use_frameworks!

def project_pods
    pod 'GiniVision', :path => '../', :testspecs => ['Tests']
    pod 'GiniVision/Networking+Pinning', :path => '../'
end

target 'Example Swift' do

    project_pods

    target 'Example_Tests' do
        inherit! :search_paths
    end

    target 'GiniVision_UITests' do
        inherit! :search_paths
    end
end

target 'Example ObjC' do
    pod 'Gini-iOS-SDK', "~> 1.4"
    project_pods
end
