source 'https://github.com/gini/gini-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'GiniVision_Example' do
    pod 'Gini-iOS-SDK', :path => '../../gini-sdk-ios/' 
    pod 'GiniVision', :path => '../'
    pod 'GiniVision/Networking+Pinning', :path => '../'

    target 'GiniVision_Tests' do
        inherit! :search_paths
    end

    target 'GiniVision_UITests' do
        inherit! :search_paths
    end
end
